apiVersion: v1
kind: Namespace
metadata:
  name: cdn-analytics
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cdn-analytics-config
  namespace: cdn-analytics
data:
  PORT: "3000"
  O2_URL: "http://openobserve-router.openobserve.svc.cluster.local:5080"
  O2_ORG: "default"
  CORS_ORIGIN: "*"
  NODE_ENV: "production"
---
apiVersion: v1
kind: Secret
metadata:
  name: cdn-analytics-secrets
  namespace: cdn-analytics
type: Opaque
stringData:
  O2_USER: "zhangxun@wanshinet.cn"
  O2_PASS: "1qaz#EDC"