apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-analytics
  namespace: cdn-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdn-analytics
  template:
    metadata:
      labels:
        app: cdn-analytics
    spec:
      containers:
        - name: app
          image: zhin1868/cdn-analytics:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: cdn-analytics-config
            - secretRef:
                name: cdn-analytics-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5